---
- name: Install a WoL script for each host
  template:
    src: wake_host.j2
    dest: "/usr/local/sbin/wol_{{ item.1.name }}"
    owner: root
    group: wheel
    mode: 0755
  with_subelements:
    - "{{ sg_networks }}"
    - hosts
    - flags:
      skip_missing: True
  loop_control:
    label: "{{ item.1.name }}"


- name: Install wakeAll script
  template:
    src: wakeAll.j2
    dest: /usr/local/sbin/wakeAll
    owner: root
    group: wheel
    mode: 0755
