---
- name: Install a WoL script for each host
  template: src=wake_host.j2 dest="/usr/local/sbin/wol_{{ item.value.name }}" owner=root group=wheel mode=0755
  with_dict: "{{ staticHosts }}"

- name: Install wakeAll script
  template: src=wakeAll.j2 dest=/usr/local/sbin/wakeAll owner=root group=wheel mode=0755
